import React from "react";
import Head from "next/head";
import withLayout from "../../layout";

const Analytics = () => {
  return (
    <div>
      {" "}
      <Head>
        <title>GAIL SIH | Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default withLayout(Analytics);
