name: GAIL Backend

on:
  push:
    branches: [SGGP-3-Backend]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build & Push Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag gail-backend:$(date +%s)
          docker push om03/gail-backend